Footer calculate back next
cschlaffner/PROTzilla2 pull request #539
Opened 2024-11-12 11:06 UTC by noLeonardo

## Description
Added footer to the run-details-page with Calculate/Next/Back.buttons and fixed scrolling.

## Changes
run-related files (`details.html, styles.css, runs.js`)

## Testing

## PR checklist
**Development**
- [ ] If necessary, I have updated the documentation (README, docstrings, etc.)
- [ ] If necessary, I have created / updated tests.
 
**Mergeability**
- [ ] main-branch has been merged into local branch to resolve conflicts
- [ ] The tests and linter have passed AFTER local merge
- [ ] The code has been formatted with `black`
 
**Code review**
- [ ] I have self-reviewed my code.
- [ ] At least one other developer reviewed and approved the changes

2024-11-12 14:40 UTC, gitjannes commented on ui/runs/static/runs/runs.js
> +    // control calculate buttons in header
```suggestion
    // control calculate buttons in footer
```

2024-11-12 14:47 UTC, gitjannes commented on ui/runs/static/runs/runs.js
> +        $("#calc_from_method").submit();
Einheitliche Benennung von den from ids wäre schön

2024-11-12 14:48 UTC, gitjannes requested changes
Sind visuell sehr schick aus, Code passt bis auf die kommentierten Sachen auch👍

2024-11-12 15:07 UTC, ronjakrg commented on ui/runs/templates/runs/details.html
> +            <div class="footer border border-end-0 border-start-0 border-bottom-0">
Instead of excluding the three borders, you can use `border-top` as well to just include the one you want :) And I'd maybe add `pt-3` so that you have the same paddings as with the borders in the navbar
But besides that, I personally like the alignment of these two buttons a lot!

2024-11-12 17:46 UTC, noLeonardo commented on ui/runs/templates/runs/details.html
> +            <div class="footer border border-end-0 border-start-0 border-bottom-0">
Thx and good optimisations, I have implemented them :)

2024-11-12 17:51 UTC, noLeonardo commented on ui/runs/static/runs/runs.js
> +        $("#calc_from_method").submit();
Danke, ich habe die Namensgebung geupdatet :)

2024-11-12 20:37 UTC, ronjakrg approved these changes

2024-11-13 12:16 UTC, gitjannes approved these changes

2024-11-13 14:13 UTC, merged