Adding Plotly Configurations
cschlaffner/PROTzilla2 pull request #544
Opened 2024-11-15 12:10 UTC by ronjakrg

## Description
fixes #<Issue Number>
Added constants to export workflow message
Added new plotly template for custom configuration for all plots
Included template in data preprocessing plots
Renamed color constants, changed the order to have the primary and secondary colors at index 0 and 1 - and included those changes in other files accordingly

## Changes
/constants/colors.py got new color names
/constants/paths.py has small change in composition of paths
/data_analysis/model_evaluation_plots.py uses new color naming
/data_analysis/plots.py uses new color naming
/data_integration/di_plots.py uses new color naming
/data_preprocessing/plots.py no longer sets manual settings for plotly, got some refactoring to be more consistent with plotly properties and methods and uses new color naming
/utilities/plot_template.py has a new plotly template which is set as default
/ui/runs/forms/data_analysis.py fixed typo in input parameter
/ui/runs/forms/data_integration.py uses new color naming
/ui/runs/views.py has new message text

## Testing

## PR checklist
**Development**
- [ ] If necessary, I have updated the documentation (README, docstrings, etc.)
- [ ] If necessary, I have created / updated tests.
 
**Mergeability**
- [ ] main-branch has been merged into local branch to resolve conflicts
- [ ] The tests and linter have passed AFTER local merge
- [ ] The code has been formatted with `black`
 
**Code review**
- [ ] I have self-reviewed my code.
- [ ] At least one other developer reviewed and approved the changes

2024-11-21 10:38 UTC, gitjannes approved these changes
Mir ist nichts unbeabsichtigtes aufgefallen. 👍

2024-11-21 12:29 UTC, sarahvgls requested changes
Finde ich voll cool, dass du dich an dieses Thema rangetraut hast und auch schon in so vielen Files Änderungen gemacht hast!! Danke dafür auf jeden Fall :) 
Ich hab ein paar kleinere Anmerkungen oder Fragen dran geschrieben, unter anderem würde ich gerne die `import *` Stellen anders behandeln, damit man dann genauer sieht, was wo in welcher File von wo verwendet wird. Kannst ja mal gerne sagen, was du dazu meinst ^^

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/constants/paths.py
>  EXTERNAL_DATA_PATH = Path(PROJECT_PATH, "user_data/external_data")
Wenn du oben die "userdata/..." paths geändert hast, wollen wir das dann in der Zeile hier auch ändern, damit es einheitlich ist?

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/data_analysis/model_evaluation_plots.py
> +from protzilla.constants.colors import *
Ich frage mich, ob es hier vielleicht sinnvoll/"Best Parctice" wäre, die Namen der Konstanten zu importieren? Dann weiß man, was es gibt, ohne dass man die andere File anschauen muss (für Code-Verständlichkeit und so, musste an SWT denken)

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/data_analysis/model_evaluation_plots.py
> +    display.plot(color=PROTZILLA_PRIMARY_COLOR)
Finde ich viel schöner mit primary color jetzt!! Danke für die Idee :)

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/data_analysis/plots.py
> +from protzilla.constants.colors import *
hier würde ich das gleiche wie oben anmerken

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/data_analysis/plots.py
> +        "A": PROTZILLA_COLOR_SEQUENCE[0],
warum hast du manchmal [0] und manchmal primary color? Wäre es da sinnvoll das irgendwie auch einheitlich zu machen?

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/data_integration/di_plots.py
> +from ..constants.colors import *
hier auch die gleiche Bemerkung wie oben, bzw könnte man hier halt genau nur die eine Konstante importieren, da nur die verwendet wird und in anderen Files wo mehr verwendet wird, dann alle importieren

2024-11-21 12:29 UTC, sarahvgls commented on protzilla/data_preprocessing/plots.py
> +    Default: PROTZILLA_SECONDARY_COLOR
Verstehe ich es richtig, dass die secondary color generell die "outlier color" ist? Wenn ja, fände ich es schön, dafür einen Kommentar in der colors.py zu haben, dann weiß man das direkt?

2024-11-21 12:29 UTC, sarahvgls commented on ui/runs/forms/data_analysis.py
> +    flip_axes = CustomChoiceField(
(Habe hier gerade noch nicht ganz den Code Überblick, daher ist die Frage vielleicht unnötig) Ist die Änderung auch an der Stelle, wo die Variable verwendet wird, angepasst oder wo wäre das dann?

2024-11-21 12:29 UTC, sarahvgls commented on ui/runs/views.py
> +            "msg": f"Workflow '{requested_workflow_name}' was exported successfully.<br>You can view the file at {WORKFLOWS_PATH}.",
Viel schöner :D

2024-11-21 19:54 UTC, ronjakrg commented on protzilla/constants/paths.py
>  EXTERNAL_DATA_PATH = Path(PROJECT_PATH, "user_data/external_data")
Ich kann hier in der Darstellung in GitHub nicht ganz erkennen, welche Zeile du meinst. Wenn ich dich richtig verstehe, meinst du den `EXTERNAL_DATA_PATH`? Das habe ich tatsächlich überlesen, dass hier auch `/user_data` drinsteckt - na klar, ändere ich!

2024-11-21 20:00 UTC, ronjakrg commented on protzilla/data_analysis/model_evaluation_plots.py
> +from protzilla.constants.colors import *
Genau das gleiche habe ich mich auch gefragt ... Meine Gedanken waren hierzu:
- Der Name `protzilla.constants.colors` sollte intuitiv genug sein, dass sich in der File halt konstante Variablen mit Farben befinden.
- Nicht unbedingt in `data_analysis`, aber in den anderen Sections werden eigentlich alle drei Variablen (Liste, primary und secondary Farben) verwendet - daher fand ich es an der Stelle sinnvoller, einfach `*` zu schreiben, statt etwas umständlich alle drei einzeln zu importieren.

Ich schreibe aber mal unten als einzelnen Kommentar, was mir gerade generell als Kompromiss einfällt! :)

2024-11-21 20:58 UTC, ronjakrg commented
### Kompromiss
(Danke an @sarahvgls für das Anstoßen der Diskussion in den Reviews!)
Ich hätte folgende Idee, auch vor dem Hintergrund der Pläne von @noLeonardo : Was haltet ihr davon, wenn wir die Konstante `PROTZILLA_COLOR_SEQUENCE` zu `PLOT_COLOR_SEQUENCE` umbenennen? Denn hier möchten wir die Farben für die Plots ablegen, die nicht unbedingt gleich mit unseren PROTzilla-Farben sind müssen. (Auch weil in Zukunft der User eigene Farben in den Settings hinterlegen können soll.)
Dazu tendiere ich dazu, die einzelnen Variablen `PROTZILLA_PRIMARY_COLOR` und `PROTZILLA_SECONDARY_COLOR` wieder rauszunehmen, und die Liste stattdessen umzusortieren, sodass an Index 0 immer die primary color und an Index 1 immer die secondary color steht, die immer für die zweifarbigen Plots verwendet werden (natürlich mit entsprechendem Hinweis im Code). Das wäre insgesamt doch konsistenter als meine vorherige Idee.

Ich bin gespannt auf Eure Meinungen hierzu! :)

2024-11-22 18:39 UTC, sarahvgls commented
Umbenennung zu PLOT_COLOR_SEQUENCE finde ich sinnvoll nach deinen genannten Gründen. 
Ich muss sagen mir gefällt es schon, dass die Konstanten Primary color und secondary color exisitieren und das sie auch direkter zu verstehen sind als Zugriff auf Stelle 0 und 1, da man wirklich gar nicht darüber nachdenken muss. Und die Zeile Code spart man sich dann auch nicht, wenn man stattdessen einen Kommenatr schreibt, der dann nur an der einen Stelle und nicht bei jeder Verwendung steht.

2024-11-24 20:37 UTC, sarahvgls approved these changes
Also ich finde es super übersichtlich und richtig toll so, vielen Dank!! :D

2024-11-24 20:37 UTC, sarahvgls commented on protzilla/constants/colors.py
> +"""Second color in list."""
Finde ich richtig schön so!!!

2024-11-25 13:47 UTC, noLeonardo approved these changes
Sieht insgesamt alles viel ordentlicher, einheitlicher und verständlicher aus und funktioniert bei mir auch :)

2024-11-25 14:17 UTC, merged