Adding Settings Menu
cschlaffner/PROTzilla2 pull request #552
Opened 2024-11-24 18:42 UTC by ronjakrg

## Description
fixes #550

- This feature enables the user to access some settings in PROTzilla by the gear icon at the top right, yay! All settings can be loaded, viewed, changed and saved. There are also default templates, if the user doesn't have their own settings yet.
- This PR also enhances the plot download: Downloaded plots are now automatically scaled to the given size, making them (almost) paper-ready.

## Changes
- Added `settings` as a new Django app
- Added and changed some HTMLs as well as methods in `views.py` to display the setting forms and plot preview
- Added default settings to `user_data/settings/`
- Added `last_view` and `run_name` to most of the view functions to enable reloading the last view after saving or canceling the settings
- Moved methods `parameter_from_post` and `convert_str_if_possible` from ui/runs/views_helper.py to protzilla/utilities/utilities.py
- Changed `steps.py` and `runs/views.py` to include scaling the downloaded plots and for fixing the `tiff` and `eps` download option.

(Please note, that the following things are not implemented yet due to the upcoming migration to React: Sticky positioning of footer, saving settings when switching to another section, moving "Manage Database" page to settings section.)

## Testing

## PR checklist
**Development**
- [x] If necessary, I have updated the documentation (README, docstrings, etc.)
- [x] If necessary, I have created / updated tests.
 
**Mergeability**
- [ ] main-branch has been merged into local branch to resolve conflicts
- [x] The tests and linter have passed AFTER local merge
- [x] The code has been formatted with `black`
 
**Code review**
- [x] I have self-reviewed my code.
- [x] At least one other developer reviewed and approved the changes

2025-02-01 21:44 UTC, ronjakrg commented
Dieser PR ist endlich ready für's Reviewen! Bitte bedenkt, dass ich die Tests für die neuen Codezeilen noch schreiben werde, freue mich aber sehr über Feedback zur Implementierung vorab! (:

2025-02-08 18:05 UTC, sarahvgls requested changes
Sehr cool!! Vielen Dank für deine Arbeit, das ist sehr cool, dass wir das jetzt haben!! 

Habe ein paar kleine Anmerkungen zum Code kommentiert. Ich würde außerdem andere default-Schriftgrößen einstellen, das könnte doch etwas verwirrend sein: 
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/3db6ca54-b07c-498b-9f85-650fd14c1adc" />

Eine Frage zu den Datenbanken in den Settings: Wollen wir nicht grundlegend die gleichen Einstellungen wie ursprünglich (aktuell auf dev-branch)? Vor allem, da es aktuell deutlich weniger der Funktionen hat oder? Mir fehlt zb die schon verfügbare Database, die ja mit dem run_protzilla skript runtergeladen wird
<img width="789" alt="image" src="https://github.com/user-attachments/assets/e48f5116-7619-4bc1-b0c6-65eeeadafaee" />

Der Code dafür müsste ja irgendwo noch stehen, den haben wir nicht gelöscht - ich kann aber gerade nicht einschätzen, wie aufwändig es ist, das hier anzuzeigen.
Wenn diese Seite erst mal als Platzhalter gedacht ist und wir uns dann wann anders uns tatsächlich darum kümmern, ist das okay - aber dann würde ich das irgendwo im Code oder sogar auf der angezeigten Seite deutlich dokumentieren, sonst geht das vllt verloren

2025-02-08 18:05 UTC, sarahvgls commented on protzilla/steps.py
> +            # TO DO: Include scale_factor here
Ist das ToDo noch aktuell?

2025-02-08 18:05 UTC, sarahvgls commented on protzilla/steps.py
> +        :return: List of all exported plots.
Vielleicht noch hinzufügen was genau ein exportierter Plot ist, also ob es die raw files sind oder metadaten als Plot objekt oder so?

2025-02-08 18:05 UTC, sarahvgls commented on protzilla/steps.py
> +        from ui.settings.plot_template import get_scale_factor
Ist es absichtlich, dass das erst hier importiert wird?

2025-02-08 18:05 UTC, sarahvgls commented on protzilla/utilities/utilities.py
> +def parameters_from_post(post):
Würde mich hier über eine kleine Dokumentation und Return-value annotation freuen, sonst ist das ohne Zusammenhang nicht so gut zu verstehen glaube ich

2025-02-08 18:05 UTC, sarahvgls commented on protzilla/utilities/utilities.py
> +def convert_str_if_possible(s):
Hier gerne auch doc-string und return type :)

2025-02-08 18:05 UTC, sarahvgls commented on ui/settings/plot_template.py
Sehr schön geschriebener Code finde ich!!

2025-02-08 18:05 UTC, sarahvgls commented on ui/settings/templates/settings_databases.html
> +                                <option value="Database 1" {% if initials.selected_database == "Database 1" %}selected{% endif %}>Database 1</option>
Was sind Database 1,2 und 3 und werden sie irgendwo wiederverwendet?

2025-02-09 11:18 UTC, ronjakrg commented on protzilla/steps.py
> +            # TO DO: Include scale_factor here
Yes, ich habe aktuell keinen Überblick, wo wir diese andere Art von Plots verwenden und wäre stark dafür, sie einfach rauszunehmen und stattdessen einheitlich Plotly verwenden. Es existiert bereits das Issue "[Use Plotly Template in all Sections #549](https://github.com/cschlaffner/PROTzilla2/issues/549)", kann aber gerne noch einen Hinweis auf dieses To Do dort einfügen.

2025-02-09 11:39 UTC, ronjakrg commented on protzilla/steps.py
> +        from ui.settings.plot_template import get_scale_factor
Ja, tatsächlich Absicht. Wenn ich das oben importiert habe, kam dieser Error (hier nur ein Ausschnitt):

```
File "/home/ronja/git/PROTzilla2/ui/runs/urls.py", line 3, in <module>
    from . import views
  File "/home/ronja/git/PROTzilla2/ui/runs/views.py", line 22, in <module>
    from protzilla.run import Run, get_available_run_names 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ronja/git/PROTzilla2/ui/../protzilla/run.py", line 8, in <module>
    from protzilla.steps import Messages, Output, Plots, Step
  File "/home/ronja/git/PROTzilla2/ui/../protzilla/steps.py", line 17, in <module>
    from ui.settings.plot_template import get_scale_factor
  File "/home/ronja/git/PROTzilla2/ui/../ui/settings/plot_template.py", line 5, in <module>
    from protzilla.disk_operator import YamlOperator
  File "/home/ronja/git/PROTzilla2/ui/../protzilla/disk_operator.py", line 14, in <module>
    from protzilla.steps import Messages, Output, Plots, Step, StepManager
ImportError: cannot import name 'Messages' from partially initialized module 'protzilla.steps' (most likely due to a circular import) (/home/ronja/git/PROTzilla2/ui/../protzilla/steps.py)
```
Also steps.py möchte Messages, Output, etc. und get_scale_factor aus dem plot_template.py importieren. Dort wird der YamlOperator aus disk_operator.py importiert, der wiederum möchte unter anderem Step aus steps.py importieren, wo dann wieder Messages, Output, etc. importiert werden soll und da fängt das ganze wieder von vorne an ... Also vermeidet das Importieren an dieser Stelle diesen circular import, weil es erst geladen wird, wenn es benötigt wird. :)

Ich fand diesen Workaround auch etwas befremdlich, habe es aber [hier](https://docs.python.org/3/faq/programming.html#id13) gefunden:

> It is sometimes necessary to move imports to a function or class to avoid problems with circular imports. Gordon McMillan says:
> 
> Circular imports are fine where both modules use the “import <module>” form of import. They fail when the 2nd module wants to grab a name out of the first (“from module import name”) and the import is at the top level. That’s because names in the 1st are not yet available, because the first module is busy importing the 2nd.
> 
> In this case, if the second module is only used in one function, then the import can easily be moved into that function. By the time the import is called, the first module will have finished initializing, and the second module can do its import.

(Sorry für die lange Antwort, aber finde es irgendwie total nice, wie wir in unseren Teilaufgaben so random stuff lernen - und vielleicht ist das ja für noch wen interessant. ^^)

2025-02-09 11:40 UTC, ronjakrg commented on protzilla/utilities/utilities.py
> +def parameters_from_post(post):
Die Methode habe ich tatsächlich einfach nur aus dem run-Kontext in utilities verschoben, damit ich sie "sauber" auch in settings nutzen kann. Aber sure, kann ich gerne noch ergänzen, da hast du Recht!

2025-02-09 11:40 UTC, ronjakrg commented on protzilla/utilities/utilities.py
> +def convert_str_if_possible(s):
Same as for `parameters_from_post`, aber ergänze ich gern! :)

2025-02-09 11:42 UTC, ronjakrg commented on ui/settings/templates/settings_databases.html
> +                                <option value="Database 1" {% if initials.selected_database == "Database 1" %}selected{% endif %}>Database 1</option>
Nee, das sind tatsächlich nur Platzhalter, da ich die Database-Sachen in diesem PR noch nicht verschieben wollte. Ich dokumentiere das aber ordentlicher, danke für's Anmerken!

2025-02-09 11:45 UTC, ronjakrg commented
> Ich würde außerdem andere default-Schriftgrößen einstellen, das könnte doch etwas verwirrend sein

Ist eigentlich schon passiert, habe nur vergessen die Änderung noch zu stagen, ups!

> Wenn diese Seite erst mal als Platzhalter gedacht ist und wir uns dann wann anders uns tatsächlich darum kümmern, ist das okay - aber dann würde ich das irgendwo im Code oder sogar auf der angezeigten Seite deutlich dokumentieren, sonst geht das vllt verloren

Genau richtig, es war als Platzhalter gedacht, da das Verschieben der Database-Logik doch etwas mehr Arbeit erfordert und ich das lieber in einem anderen PR erledigen (lassen) würde. Es gibt auch schon Issues dazu, dass es manchmal nicht funktioniert, und uns sind ja auch schon weirde Dinge in den Tests aufgefallen. Würde es lieber als ein "Refactoring Databases" Arbeitspaket sehen. Aber danke für Deinen Hinweis, werde das im Code besser dokumentieren und gleich mal ein Issue dazu aufmachen, damit wir das auf dem Schirm haben. (:
_Edit:_ Issue ist erstellt, siehe #571.

2025-02-10 07:15 UTC, sarahvgls commented on protzilla/steps.py
> +        from ui.settings.plot_template import get_scale_factor
Oki danke für die Erklärung!! Ja, das habe ich auch erst mit Protzilla gelernt, dass man das tatsächlich so macht :D

2025-02-10 07:15 UTC, sarahvgls commented on protzilla/utilities/utilities.py
> +def convert_str_if_possible(s):
Danke, dass du es trotzdem ergänzt hast ^^

2025-02-10 07:20 UTC, hendraet commented on protzilla/steps.py
> +        from ui.settings.plot_template import get_scale_factor
Also ich fand die lange Antwort interessant :D

2025-02-10 07:30 UTC, sarahvgls approved these changes
Danke für die Änderungen, Antworten und die Erklärungen!! ^^

Hatte noch eine Idee, ob man vielleicht einen "reset to default" button hinzufügen möchte, sag aber gerne mal Bescheid, was du davon hältst :))

2025-02-10 07:30 UTC, sarahvgls commented on user_data/settings/plots_default.yaml
> -height: 40
Bei mir sah es jetzt trotzdem wieder so aus wie im letzten Screenshot, kommt aber vermutlich daher, dass ich es das letzte mal doch gespeichert habe und dann die default werte ja "überschrieben" werden in plots.yaml. Man könnte überlegen, ob sich ein "reset to default" Button lohnt, der einfach wieder plots.yaml mit plots_default.yaml überschreibt für solche Fälle bzw. falls man mal falsch konfiguriert und sich nicht mehr erinnern kann was sinnvoll aussah? Wäre nur ein grober Vorschlag, weiß nicht, ob es unbedingt umgesetzt werden muss :)))

2025-02-10 07:30 UTC, sarahvgls commented on ui/settings/templates/settings_databases.html
> +
Ahh fair... Habe ich übersehen haha

2025-02-10 12:27 UTC, ronjakrg commented on protzilla/steps.py
> +        from ui.settings.plot_template import get_scale_factor
Ach, du liest hier auch mit? 👋 Das freut mich zu hören haha (:

2025-02-10 12:37 UTC, ronjakrg commented on user_data/settings/plots_default.yaml
> -height: 40
Ein "Should have" war ja die Selection von mehreren gespeicherten Plotly-Templates, zum Beispiel je Publikation (mit verschiedenen Guidelines) an der man arbeitet. Und da fänd ich es super sinnvoll, wie du es sagst, eine default Option zum Auswählen zu haben! Würde ich dann nach unserer Migration aufnehmen wollen. :)

2025-02-10 12:38 UTC, ronjakrg commented on ui/settings/templates/settings_databases.html
> +
Alles fine, finde es so nochmal deutlich einleuchtender! (:

2025-02-10 23:46 UTC, noLeonardo requested changes
Es ist echt ein tolles Feature, dass wir jetzt Plots an einer Stelle einheitlich formatieren können, und auch den Demo-Plot finde ich sehr toll :)

Bei mir bugt die UI noch ein ganz wenig rum, was vermutlich daran liegt, dass der Content etwas breiter als der Screen ist. Da wäre vielleicht noch eine overflow-x Option und etwas mehr Spacing zu den Linien passend. Aber mit React wird das ja bestimmt deutlich besser und einfacher.

Eine zukünftige Idee wäre vielleicht noch, den Demo-Plot in der echten mm-Größe zu rendern, damit ich direkt sehen kann, wie groß meine Plots exportiert werden. 

Insgesamt toller und auch viel Code, der aber bei meinem Testen gut funktioniert hat 🚀

2025-02-10 23:46 UTC, noLeonardo commented on .gitignore
Wenn ich den Server starte wird irgendwie die Datei ui/db.sqlite3 geändert, ist die Änderung oder die Datei relvant oder könnten wir diese auch ins gitignore aufnehmen?

2025-02-10 23:46 UTC, noLeonardo commented on ui/settings/apps.py
> +class SettingsV2Config(AppConfig):
Warum ist hier die SettingsConfig V2, gibt es davon mehrere?

2025-02-10 23:46 UTC, noLeonardo commented on ui/settings/plot_template.py
> +    pt_to_mm = 1 / 72 * 24.5
Was wird hier berechnet? Vielleicht können einzelne Werte als Konstanten ausgelagert werden.

2025-02-10 23:46 UTC, noLeonardo commented on ui/settings/static/settings.js
> +
Das `document.getElementById` kann in dieser Datei an ein paar Stellen verkürzt werden.

```suggestion
    $("#customFontInput").click(function () {
        $("#customFontRadio").prop("checked", true);
    });
    
```

2025-02-11 08:43 UTC, ronjakrg commented on .gitignore
Das kam bei mir auch manchmal vor, keine Ahnung woran das liegt ...

2025-02-11 08:53 UTC, ronjakrg commented on ui/settings/apps.py
> +class SettingsV2Config(AppConfig):
Ah, das ist copy pasta aus `ui/runs/apps.py`, da stand `RunsV2Config`. Ändere ich!

2025-02-11 08:55 UTC, ronjakrg commented on ui/settings/plot_template.py
> +    pt_to_mm = 1 / 72 * 24.5
1 pt sind 1/72 Zoll und 1 Zoll sind 24.5 mm. Dachte das wird durch die Benennung `pt_to_mm` klar, was würdest du sonst vorschlagen, damit es klarer wird?

2025-02-11 09:57 UTC, noLeonardo commented on ui/settings/plot_template.py
> +    pt_to_mm = 1 / 72 * 24.5
Die Umrechnung wird schon klar, stimmt. Aber ist ein Zoll nicht 25.4mm? In der Datei steht unten auch nochmal 24.5, vielleicht könntest du es nach oben auslagern, so wie die Konstante `SCALED_WIDTH`.

2025-02-11 09:57 UTC, noLeonardo commented on ui/settings/plot_template.py
> +    scale_factor = (params["width"] / 24.5 * dpi) / current_width
hier, steht es nochmal

2025-02-11 10:58 UTC, ronjakrg commented on ui/settings/plot_template.py
> +    pt_to_mm = 1 / 72 * 24.5
Oh stimmt, einmal ist es ein Typo. Lagere das mal als Kontanten aus, schau es dir gerne nochmal an! :)

2025-02-11 11:09 UTC, ronjakrg commented
> Bei mir bugt die UI noch ein ganz wenig rum, was vermutlich daran liegt, dass der Content etwas breiter als der Screen ist. Da wäre vielleicht noch eine overflow-x Option und etwas mehr Spacing zu den Linien passend. Aber mit React wird das ja bestimmt deutlich besser und einfacher.

Ja, das hab ich aktuell mit den 600px in der Breite hardgecoded, weil das in React eh nochmal anders wird. ^

> Eine zukünftige Idee wäre vielleicht noch, den Demo-Plot in der echten mm-Größe zu rendern, damit ich direkt sehen kann, wie groß meine Plots exportiert werden.

Das ist leider nicht so einfach, weil die "echte mm-Größe" von der Auflösung des anzeigenden Monitors oder auch von deinem Browser abhängt. Daher ist hier die Idee, den Plot im richtigen Verhältnis zwischen Länge und Breite anzuzeigen.

2025-02-17 13:23 UTC, noLeonardo approved these changes

2025-02-18 13:55 UTC, merged