color selection for enrichment analysis bar plot
cschlaffner/PROTzilla2 pull request #556
Opened 2024-11-27 17:23 UTC by noLeonardo

## Description
merged the selection form, from gen_sets selection and color selection to a single form

## Changes
custom field
form for enrichment analysis bar blot

## Testing

## PR checklist
**Development**
- [ ] If necessary, I have updated the documentation (README, docstrings, etc.)
- [ ] If necessary, I have created / updated tests.
 
**Mergeability**
- [ ] main-branch has been merged into local branch to resolve conflicts
- [ ] The tests and linter have passed AFTER local merge
- [ ] The code has been formatted with `black`
 
**Code review**
- [ ] I have self-reviewed my code.
- [ ] At least one other developer reviewed and approved the changes

2024-12-17 13:37 UTC, gitjannes requested changes

2024-12-17 13:37 UTC, gitjannes commented on ui/runs/forms/custom_fields.py
> +                choices=[(el.value, el.value) for el in choices],
Das "el in choices" ist nicht so clean, benenne das lieber in sowas wie choice in choices um. Gerne dann auch für den Rest der Datei 👍

2024-12-17 13:37 UTC, gitjannes commented on tests/protzilla/data_integration/test_plots_data_integration.py
> +        gene_sets={"KEGG" : "#E2A46D", "Process" : "#4A536A"},
Die ganzen Hex-Strings gerne als Variable zusammengefasst, sodass man die mit einem Mal alle ändern kann.

2024-12-17 13:37 UTC, gitjannes commented on ui/runs/forms/data_integration.py
> +    # TODO: update PLOT_COLOR_SEQUENCE (color, color) for color in PLOT_COLOR_SEQUENCE
Schön schonmal an die kommenden Schritte gedacht, aber  mach bitte noch ne Karte im Notion draus und referenziere im Todo, wann genau das umgesetzt werden kann.

2024-12-17 22:16 UTC, noLeonardo commented on tests/protzilla/data_integration/test_plots_data_integration.py
> +        gene_sets={"KEGG" : "#E2A46D", "Process" : "#4A536A"},
Vielen Dank für die Idee, aber diese wäre an dieser Stelle nicht passend, da es sich um eine Test-Datei handelt. Die erstellten Plots werden nicht visuell betrachtet. An dieser Stelle ist viel mehr wichtig, dass sich der Dateityp von List zu Dict geändert hat und direkt ersichtlich werden soll, dass es sich um einen HEX-Farbwert handelt. Bei einem fehlgeschlagenen Test ist somit direkt klar, welche Parameter zu einem Fail geführt haben.

2025-01-18 09:34 UTC, sarahvgls requested changes
Tut mir mega leid, dass dein PR da so lange rumlag und sich keiner mehr darum gekümmert hat, das soll natürlich nicht passieren!! Ich hab ein paar Kleinigkeiten angemerkt, aber sollte nur ganz wenig Arbeit noch mal sein, ansonsten finde ich es richtig gut!!! Danke, dass du dich darum gekümmert hast :D

2025-01-18 09:34 UTC, sarahvgls commented on protzilla/data_integration/di_plots.py
> +    gene_sets={},
Wenn hier von Liste zu Set geändert wird wäre es super, wenn das auch in den Docs (l. 31) angepasst wird

2025-01-18 09:34 UTC, sarahvgls commented on ui/runs/forms/data_integration.py
> +            )  #  check whether we need to pass the organism name here
Warum wurde hier an so vielen Stellen das TODO weggenommen? Wurde es erledigt?

2025-01-18 09:34 UTC, sarahvgls commented on ui/runs/forms/data_integration.py
> +    # TODO: after the color naming has been optimised in all filese, the underlying line can be updated: (color, color) for color in PLOT_COLOR_SEQUENCE
Hab gesehen, dass Jannes hierzu auch einen Kommentar gemacht hatte: Tbh muss ich sagen, dass ich von der Notion Card so nicht ganz verstehe, dass das damit gemeint sein soll - entweder fände ich es schöln, wenn du es da ausführlicher beschreibst, sodass jeder es umsetzen könnte - oder du claimst es direkt für dich und übernimmst die Verantwortung?

2025-01-18 09:34 UTC, sarahvgls commented on ui/runs/forms/custom_fields.py
> +                choices=[(choice.value, choice.value) for choice in choices],
so viel lesbarer, nice!!

2025-01-18 09:34 UTC, sarahvgls commented on ui/runs/forms/custom_fields.py
> +    def clean(self, value: list[str] | None):
Für Dokumentation und Klarheit wäre es schön, wenn hier noch ein return type annotiert wäre :)

2025-01-18 09:34 UTC, sarahvgls commented on ui/runs/templates/runs/field_component_color_selection.html
Ich fände es persönlich schöner, wenn zwischen den drop down menus etwas mehr spacing wäre, aaaaber finde das gerade nicht relevant genug dafür das Frontend vor React gerade anzufassen, also schieben wir das gerne auf!!

2025-01-20 15:42 UTC, gitjannes reviewed
👍

2025-01-22 17:18 UTC, noLeonardo commented on ui/runs/forms/data_integration.py
> +            )  #  check whether we need to pass the organism name here
Weird sollte nicht so sein, sind jetzt alle wieder da 😄

2025-01-22 17:19 UTC, noLeonardo commented on ui/runs/forms/data_integration.py
> +    # TODO: after the color naming has been optimised in all filese, the underlying line can be updated: (color, color) for color in PLOT_COLOR_SEQUENCE
Ich hab die Notion-Card jetzt etwas ausführlicher geschrieben. Im neuen Projekt kann ich mir aber auch gut vorstellen, dass wir es von Anfang an besser implementieren.

2025-01-22 21:12 UTC, sarahvgls commented on ui/runs/forms/data_integration.py
> +    # TODO: after the color naming has been optimised in all filese, the underlying line can be updated: (color, color) for color in PLOT_COLOR_SEQUENCE
Supi!

2025-01-22 21:14 UTC, sarahvgls approved these changes
Danke für die Anpassungen! Und gute Besserung, arbeite mal nicht zu viel wenn du krank bist!! :)

2025-01-23 11:14 UTC, gitjannes approved these changes

2025-01-23 18:43 UTC, merged