Jump between steps
cschlaffner/PROTzilla2 pull request #561
Opened 2024-12-11 14:46 UTC by pchklm

This PR enables the user to skip between steps in order to quickly change parameters and then recalculate the entire workflow.

## Changes
Everywhere o7

## Testing
Test if steps still get correctly calculated.

## PR checklist
**Development**
- [ ] If necessary, I have updated the documentation (README, docstrings, etc.)
- [ ] If necessary, I have created / updated tests.
 
**Mergeability**
- [ ] main-branch has been merged into local branch to resolve conflicts
- [ ] The tests and linter have passed AFTER local merge
 
**Code review**
- [ ] I have self-reviewed my code.
- [ ] At least one other developer reviewed and approved the changes

2024-12-18 08:30 UTC, henninggaertner commented
You should take a look at #515 if you haven't yet to see whether this should be combined

2025-01-10 18:09 UTC, ronjakrg commented
Is this already open for review or still a draft? I tried testing the new icons and apparently the "Calculate"-Button doesn't seem to work and if I open an existing run, all icons are set to the empty circle, although I have already calculated a few steps.

2025-02-03 08:59 UTC, ronjakrg requested changes
Sehr schöner und verständlicher Code, und bereichert die Usability von PROTzilla enorm! 🔥 Habe nur kleinere Anmerkungen gemacht, zum Beispiel fehlende Leerzeichen und ein paar überflüssige Print-Statements. :)

2025-02-03 08:59 UTC, ronjakrg commented on protzilla/run.py
> +    def step_set_outdated(self,offset: int = 0) -> int:
```suggestion
    def step_set_outdated(self, offset: int = 0) -> int:
```

2025-02-03 08:59 UTC, ronjakrg commented on protzilla/steps.py
> +    calculation_status: Literal["complete","outdated","incomplete","failed"] = "incomplete"
```suggestion
    calculation_status: Literal["complete", "outdated", "incomplete", "failed"] = "incomplete"
```

2025-02-03 08:59 UTC, ronjakrg commented on protzilla/steps.py
> +            if str(e)!="":
Wieso hast du das hier ergänzt? In welchem Fall ist e leer und wieso fangen wir das dann nicht ab? :)

2025-02-03 08:59 UTC, ronjakrg commented on protzilla/steps.py
> +                raise Exception("")
Ah, hier beantwortet sich meine Frage von oben 😅 Würde sich hier aber anbieten, einen Text zu ergänzen, oder?

2025-02-03 08:59 UTC, ronjakrg commented on protzilla/steps.py
> +    def set_steps_outdated(self, offset:int) -> None:
```suggestion
    def set_steps_outdated(self, offset: int) -> None:
```

2025-02-03 08:59 UTC, ronjakrg commented on ui/runs/forms/base.py
> +        print("submit", self)
Das hier sollte vermutlich nicht mehr hier stehen, oder? ^^

2025-02-03 08:59 UTC, ronjakrg commented on ui/runs/forms/base.py
> +        print("update", self)
Hier auch?

2025-02-03 08:59 UTC, ronjakrg commented on ui/runs/static/runs/runs.js
> +                    console.log("gg")
Fühl ich sehr, aber sollten wir für's Mergen rausnehmen :D

2025-02-03 08:59 UTC, ronjakrg commented on ui/runs/views.py
> +    count=0
```suggestion
    count = 0
```

2025-02-08 15:01 UTC, sarahvgls requested changes
🐛 BUG 🐛 
Ich finde es beeindruckend schade, dass die Tests das nicht abfangen, aber ich kann keinen Run erstellen lol. (Und auch keinen bisherigen testen) 
Ich weiß nicht ganz woran es liegt, ob ich vielleicht irgendetwas falsch mache, aber das hier sind meine Beobachtungen: Ich dachte erst es wäre weil die Änderungen nicht backwards-compatible sind - was kein Problem gewesen wäre- aber ich kann leider auch keine Neuen erstellen. Das ist leider für die usability nicht ganz so praktisch haha 

Die Landing Page startet und kann wie erwartet verwendet werden. Sobald ich einen alten Run öffne oder einen neuen erstelle können keine Schritte ausgeführt werden. Vielleicht funktioniert der calculate button nicht? Wenn ich clicke, sieht der Button ausgewählt aus (leichter roter Rahmen drum herum), aber es folgt keine Funktion - auch im Backend kommt nichts an: 

>[2025/02/08 - 14:50:09] [    INFO] Reading yaml from /Users/sarah/Documents/HPI/WS_24_25/BP-Renard/project/PROTzilla2/user_data/workflows/standard.yaml
[2025/02/08 - 14:50:09] [    INFO] "POST /runs/create HTTP/1.1" 302 0
[2025/02/08 - 14:50:09] [    INFO] "GET /runs/detail/test_new_skipping HTTP/1.1" 200 122168
[2025/02/08 - 14:50:09] [    INFO] "GET /static/img/incomplete_icon.svg HTTP/1.1" 304 0 

Wenn ich reloade folgt jedes Mal das:

> [2025/02/08 - 14:51:15] [    INFO] "GET /runs/detail/test_new_skipping HTTP/1.1" 200 122168
[2025/02/08 - 14:51:15] [    INFO] "GET /static/img/incomplete_icon.svg HTTP/1.1" 304 0

Ich kann zwischen den Schritten springen, aber es passiert halt nichts. Wenn ich andere Schritte als den Ersten versuche zu calculaten passiert gar nichts im Backend.

(Tests laufen problemlos durch leider)

2025-02-08 15:37 UTC, sarahvgls commented
Habe nach etwas rumprobieren herausgefunden, dass der Unterschied an der Adresse liegt über die man PROTzilla aufruft: 
Auf 127.0.01 funktioniert es - auf localhost (meinem Lesezeichen haha) **nicht** (port ist der gleiche).
Ich glaube das wäre etwas, was man sich noch mal anschauen sollte, da das unerwartetes Verhalten ist. Eigentlich sollten die beiden Adressen genau das gleiche Verhalten widerspiegeln...
(Auf 0.0.0.0, der dritten unserer erlaubten Adressen nach Django Settings (ui/main/settings.py) geht es auch!)

2025-02-08 16:22 UTC, sarahvgls reviewed
Abgesehen vom localhost bug finde ich es super! Vielen Dank! 
Ein paar kleine Anmerkungen von mir auch noch, aber sonst spitze :))

2025-02-08 16:22 UTC, sarahvgls commented on protzilla/steps.py
> +                raise Exception("")
Würde auch vorschlagen entweder ein erklärende Kommentar oder eine beschreibende Exception, dass das nicht relevant ist abzufangen?

2025-02-08 16:22 UTC, sarahvgls commented on protzilla/steps.py
> +        :param step_type: The type of the step as a class objectresults_exist
Soll das da sein? Sonst wurde an der Methode nichts verändert oder?

2025-02-08 16:22 UTC, sarahvgls commented on protzilla/run_v2.py
> +
Das bitte löschen, damit wir run_v2 gar nicht anfassen oder?

2025-02-08 16:22 UTC, sarahvgls commented on tests/protzilla/test_runner.py
>          # side effect to mark the step as finished
Der Kommentar könnte jetzt einfach weggelassen werden, da das vom Code her verständlich ist oder?

2025-02-08 16:22 UTC, sarahvgls commented on tests/protzilla/test_run.py
> +        run_imported.step_goto(0, "data_preprocessing_wrong")
Warum wurde das geändert? Testet es dann nicht etwas ganz anderes?

2025-02-11 23:01 UTC, pchklm commented on tests/protzilla/test_run.py
> +        run_imported.step_goto(0, "data_preprocessing_wrong")
Hier wurde getestet, dass wenn man nach vorne springen will, das nicht funktioniert. Aber genau die Funktionalität wurde ja umgeschrieben. Jetzt probiert er halt zu einem Step einer nicht existierenden Section zu springen. Der Test macht also bisschen was anderes aber hatte ihn trotzdem einfach mal drin gelassen weil mehr Tests immer gut :)

2025-02-11 23:08 UTC, pchklm commented
> Habe nach etwas rumprobieren herausgefunden, dass der Unterschied an der Adresse liegt über die man PROTzilla aufruft: Auf 127.0.01 funktioniert es - auf localhost (meinem Lesezeichen haha) **nicht** (port ist der gleiche). Ich glaube das wäre etwas, was man sich noch mal anschauen sollte, da das unerwartetes Verhalten ist. Eigentlich sollten die beiden Adressen genau das gleiche Verhalten widerspiegeln... (Auf 0.0.0.0, der dritten unserer erlaubten Adressen nach Django Settings (ui/main/settings.py) geht es auch!)

Hm, habs bei mir gerade mal getestet und bei mir funktioniert auch über localhost alles. Idk ob es da noch UNterschiede je nach Betriebssystem oder so gibt.

2025-02-12 09:10 UTC, ronjakrg approved these changes

2025-02-13 20:30 UTC, sarahvgls commented on tests/protzilla/test_run.py
> +        run_imported.step_goto(0, "data_preprocessing_wrong")
Ahh fair! Dann sinnvoll :))

2025-02-13 20:39 UTC, sarahvgls approved these changes

2025-02-13 20:43 UTC, sarahvgls commented
Ich hab noch eine inhaltliche Frage: Wenn ich zb bei unserem Standard Workflow die steps in einer chaotischen Reihenfolge calculate (erst zweites Filter, dann imputation und dann erstes Filtern) Was passiert dann wenn mit dem nächsten Schritt der ausgeführt wird: Nimmt dieser den gefilterten und imputeten Inhalt von allen drei schritten (also werden die noch mal durchgecalculated) oder nur von zweitem Filter + imputation? 
Ersteres fände ich sinnvoll, habe mich aber gerade beim ausprobieren gefragt, ob das nicht vielleicht anders ist und dann zu Fehlern führen könnte

2025-02-13 20:47 UTC, sarahvgls commented
Übrigens: es geht plötzlich auf localhost. Ich habe leider keine Ahnung warum - ich hoffe mal, ich hatte irgendwas falsch gemacht haha

2025-02-17 11:41 UTC, merged